apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://vana-prometheus.internal.gentlesea-17ccac60.germanywestcentral.azurecontainerapps.io
    isDefault: true
    editable: false
